/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Sky.Cat;


import Sky.Listener.Event;
import Sky.Listener.EventListener;
import Sky.Listener.EventType;
import dbConnect.DBConnect;

import javax.swing.*;
import java.awt.*;
import java.util.List;

public class DeleteRequest extends javax.swing.JFrame {

    public DeleteRequest() {
        initComponents();

        getContentPane().setBackground(new Color(165,196,221));

        fillComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelButton = new javax.swing.JButton();
        deleteRequestButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        requestNameField = new javax.swing.JTextField();
        requestEmailField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        requestTypeField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestDetailField = new javax.swing.JTextArea();
        requestDateField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        requestIdCombox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Delete Request");
        setAlwaysOnTop(true);
        setLocationByPlatform(true);

        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        deleteRequestButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteRequestButton.setText("Delete Request");
        deleteRequestButton.setToolTipText("Delete the selected request from the database");
        deleteRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRequestButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Requester's Name");

        jLabel2.setText("Day of request");

        requestNameField.setEditable(false);

        requestEmailField.setEditable(false);

        jLabel4.setText("Requester's Email");

        requestTypeField.setEditable(false);
        requestTypeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTypeFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Request Type");

        jLabel7.setText("Request details");

        requestDetailField.setEditable(false);
        requestDetailField.setColumns(20);
        requestDetailField.setLineWrap(true);
        requestDetailField.setRows(3);
        jScrollPane1.setViewportView(requestDetailField);

        requestDateField.setEditable(false);

        jLabel9.setText("Request ID");

        requestIdCombox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestIdComboxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel3.setText("Select an ID");

        clearButton.setText("Clear selection");
        clearButton.setToolTipText("Reset the selected choice");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(requestNameField)
                            .addComponent(requestEmailField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(requestTypeField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                            .addComponent(requestDateField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(requestIdCombox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(clearButton)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(deleteRequestButton)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton)
                        .addGap(100, 100, 100))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(requestIdCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton))
                .addGap(1, 1, 1)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(requestNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(requestDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(requestTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteRequestButton)
                            .addComponent(cancelButton)))
                    .addComponent(jLabel7))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void requestTypeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTypeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requestTypeFieldActionPerformed

    private void deleteRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRequestButtonActionPerformed
        deleteRequest();

        EventListener.inform(new Event(EventType.DataEvent));
    }//GEN-LAST:event_deleteRequestButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clearFormFields();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void requestIdComboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestIdComboxActionPerformed
        ITRequest itRequest = (ITRequest) requestIdCombox.getSelectedItem();

        if (itRequest != null) {
            requestDateField.setText(String.valueOf(itRequest.getReqDate()));
            requestEmailField.setText(itRequest.getReqEmail());
            requestNameField.setText(itRequest.getReqName());
            requestDetailField.setText(itRequest.getReqDetails());
            requestTypeField.setText(itRequest.getReqType());
        }
    }//GEN-LAST:event_requestIdComboxActionPerformed

    private void clearFormFields() {
        requestTypeField.setText(null);
        requestDateField.setText(null);
        requestDetailField.setText(null);
        requestEmailField.setText(null);
        requestNameField.setText(null);
        requestIdCombox.setSelectedIndex(-1);
    }

    private void fillComboBox() {
        try {
            List<ITRequest> itRequestList = DBConnect.retrieveAll(ITRequest.class);
            for (ITRequest itRequest : itRequestList) {
                requestIdCombox.addItem(itRequest);
            }
            clearFormFields();
        } catch (Exception e) {
            System.out.println("There was issue loading combo box\'s content");
        }
    }

    private void updateScreen() {
        requestIdCombox.removeAllItems();
        fillComboBox();
    }

    private void deleteRequest() {
        try {
            int id = ((ITRequest) requestIdCombox.getSelectedItem()).getReqID();

            ITRequest itRequest = new ITRequest();
            itRequest.setReqID(id);

            boolean success = DBConnect.delete(itRequest);
            if (success) {
                javax.swing.JOptionPane.showMessageDialog(this, "Request removed from database!", "Successes", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                updateScreen();
                clearFormFields();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Cannot remove request", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Cannot remove request. Problem founded: \n >" + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    public static void main(String[] args) {
        try {
            UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteRequest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton deleteRequestButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField requestDateField;
    private javax.swing.JTextArea requestDetailField;
    private javax.swing.JTextField requestEmailField;
    private javax.swing.JComboBox<ITRequest> requestIdCombox;
    private javax.swing.JTextField requestNameField;
    private javax.swing.JTextField requestTypeField;
    // End of variables declaration//GEN-END:variables
}
