/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Sky.Cat;


import Sky.Cat.model.Product;
import Sky.Listener.Event;
import Sky.Listener.EventListener;
import Sky.Listener.EventType;
import dbConnect.DBConnect;
import dbConnect.models.json.JsonUtility;

import javax.swing.*;
import java.awt.*;
import java.text.SimpleDateFormat;
import java.util.List;

public class DeleteProduct extends javax.swing.JFrame {

    public DeleteProduct() {
        initComponents();

        getContentPane().setBackground(new Color(165,196,221));
        loadProductComboBox();
        fillComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelButton = new javax.swing.JButton();
        deleteProductButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        importPriceField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        detailWarnLabel = new javax.swing.JLabel();
        productNameField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        warrantyField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        colorsTextArea = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        specificationsTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        categoriesTextArea = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        profitRateField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        featuresTextArea = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        accessoriesTextArea = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        isBusinessModelCheckbox = new javax.swing.JCheckBox();
        productIdComboBox = new javax.swing.JComboBox<>();
        companyCodeField = new javax.swing.JTextField();
        stockQuantityField = new javax.swing.JTextField();
        importDateField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Delete Product");
        setAlwaysOnTop(true);
        setLocationByPlatform(true);

        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        deleteProductButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteProductButton.setText("Delete Product");
        deleteProductButton.setToolTipText("Delete an existing product in the database");
        deleteProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProductButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Product Code");

        jLabel2.setText("Product Name");

        importPriceField.setEditable(false);

        jLabel4.setText("Import Price");

        jLabel7.setText("Company Code");

        productNameField.setEditable(false);

        jLabel9.setText("Profit Rate");

        jLabel3.setText("Import Date");

        jLabel5.setText("Spec. (JSON)");

        warrantyField.setEditable(false);

        jLabel6.setText("Warranty");

        colorsTextArea.setEditable(false);
        colorsTextArea.setColumns(20);
        colorsTextArea.setRows(5);
        jScrollPane1.setViewportView(colorsTextArea);

        jLabel8.setText("Categories");

        specificationsTextArea.setEditable(false);
        specificationsTextArea.setColumns(20);
        specificationsTextArea.setRows(5);
        jScrollPane2.setViewportView(specificationsTextArea);

        categoriesTextArea.setEditable(false);
        categoriesTextArea.setColumns(20);
        categoriesTextArea.setRows(5);
        jScrollPane3.setViewportView(categoriesTextArea);

        jLabel10.setText("Colors");

        profitRateField.setEditable(false);

        jLabel12.setText("Stock Quantity");

        featuresTextArea.setEditable(false);
        featuresTextArea.setColumns(20);
        featuresTextArea.setRows(5);
        jScrollPane4.setViewportView(featuresTextArea);

        accessoriesTextArea.setEditable(false);
        accessoriesTextArea.setColumns(20);
        accessoriesTextArea.setRows(5);
        jScrollPane5.setViewportView(accessoriesTextArea);

        jLabel15.setText("Accessories");

        jLabel16.setText("Features");

        isBusinessModelCheckbox.setText("Is Business Model");
        isBusinessModelCheckbox.setEnabled(false);

        productIdComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productIdComboBoxActionPerformed(evt);
            }
        });

        companyCodeField.setEditable(false);

        stockQuantityField.setEditable(false);

        importDateField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel3))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane3)
                                    .addComponent(jScrollPane2)
                                    .addComponent(warrantyField)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(importPriceField, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                                    .addComponent(productIdComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(24, 24, 24)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(productNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(importDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(285, 285, 285)
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(profitRateField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(isBusinessModelCheckbox))
                                        .addGap(1, 1, 1))
                                    .addComponent(jScrollPane4)
                                    .addComponent(jScrollPane5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(stockQuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(companyCodeField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deleteProductButton)
                                .addGap(18, 18, 18)
                                .addComponent(cancelButton)))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(detailWarnLabel)
                        .addGap(6, 6, 6))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(productIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(importPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profitRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(companyCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel12)
                    .addComponent(stockQuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(importDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(isBusinessModelCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(warrantyField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(detailWarnLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(deleteProductButton))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void deleteProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProductButtonActionPerformed
        deleteProduct();

        EventListener.inform(new Event(EventType.DataEvent));
    }//GEN-LAST:event_deleteProductButtonActionPerformed

    private void productIdComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productIdComboBoxActionPerformed
        Product selectedProduct = (Product) productIdComboBox.getSelectedItem();

        if (selectedProduct != null) {
            try {
                productNameField.setText(selectedProduct.getProductName());
                importPriceField.setText(String.valueOf(selectedProduct.getImportPrice()));
                profitRateField.setText(String.valueOf(selectedProduct.getProfitRate()));
                if (selectedProduct.getCompanyCode() != null) {
                    companyCodeField.setText(selectedProduct.getCompanyCode());
                }

                if (selectedProduct.getImportDate() != null) {
                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                    String date = dateFormat.format(selectedProduct.getImportDate());
                    importDateField.setText(date);
                }

                stockQuantityField.setText(Integer.toString(selectedProduct.getStockQuantity()));

                warrantyField.setText(selectedProduct.getWarranty() != null ? selectedProduct.getWarranty() : "");
                isBusinessModelCheckbox.setSelected(selectedProduct.isBusinessModel());

                if (selectedProduct.getSpecifications() != null) {
                    specificationsTextArea.setText(JsonUtility.toJson(selectedProduct.getSpecifications()));
                }

                if (selectedProduct.getCategories() != null && !selectedProduct.getCategories().isEmpty()) {
                    String categories = String.join(", ", selectedProduct.getCategories());
                    categoriesTextArea.setText(categories);
                }

                if (selectedProduct.getColorsAvailable() != null && !selectedProduct.getColorsAvailable().isEmpty()) {
                    String colors = String.join(", ", selectedProduct.getColorsAvailable());
                    colorsTextArea.setText(colors);
                }

                if (selectedProduct.getAccessories() != null && !selectedProduct.getAccessories().isEmpty()) {
                    String accessories = String.join(", ", selectedProduct.getAccessories());
                    accessoriesTextArea.setText(accessories);
                }

                if (selectedProduct.getFeatures() != null && !selectedProduct.getFeatures().isEmpty()) {
                    String features = String.join(", ", selectedProduct.getAccessories());
                    featuresTextArea.setText(features);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error loading product data: " + e.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
                System.out.println("Error populating product fields: " + e.getMessage());
            }

        }
    }//GEN-LAST:event_productIdComboBoxActionPerformed

    private void clearProductFields() {
        productIdComboBox.setSelectedItem(-1);
        productNameField.setText("");
        importPriceField.setText("");
        profitRateField.setText("");
        companyCodeField.setText("");
        importDateField.setText("");
        stockQuantityField.setText("");
        warrantyField.setText("");
        isBusinessModelCheckbox.setSelected(false);
        specificationsTextArea.setText("");
        categoriesTextArea.setText("");
        colorsTextArea.setText("");
        accessoriesTextArea.setText("");
        featuresTextArea.setText("");
    }

    private void deleteProduct() {
        try {
            Product selectedProduct = (Product) productIdComboBox.getSelectedItem();
            if (selectedProduct == null) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Please select a product to delete", "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            String productCode = selectedProduct.getProductCode();
            Product product = new Product();
            product.setProductCode(productCode);

            boolean success = DBConnect.delete(product);
            if (success) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Product removed from database!", "Success",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
                updateScreen();
                clearProductFields();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Cannot remove product", "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Cannot remove product: " + e.getMessage(), "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void loadProductComboBox() {
        try {
            List<Product> products = DBConnect.retrieveAll(Product.class);
            productIdComboBox.removeAllItems();
            for (Product product : products) {
                productIdComboBox.addItem(product);
            }
        } catch (Exception e) {
            System.out.println("Error loading products: " + e.getMessage());
        }
    }

    private void fillComboBox() {
        try {
            List<Product> products = DBConnect.retrieveAll(Product.class);
            productIdComboBox.removeAllItems();
            for (Product product : products) {
                productIdComboBox.addItem(product);
            }
        } catch (Exception e) {
            System.out.println("Error loading specific product: " + e.getMessage());
        }
    }

    private void updateScreen() {
        productIdComboBox.removeAllItems();
        loadProductComboBox();
    }

    public static void main(String[] args) {
        try {
            UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea accessoriesTextArea;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextArea categoriesTextArea;
    private javax.swing.JTextArea colorsTextArea;
    private javax.swing.JTextField companyCodeField;
    private javax.swing.JButton deleteProductButton;
    private javax.swing.JLabel detailWarnLabel;
    private javax.swing.JTextArea featuresTextArea;
    private javax.swing.JTextField importDateField;
    private javax.swing.JTextField importPriceField;
    private javax.swing.JCheckBox isBusinessModelCheckbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JComboBox<Product> productIdComboBox;
    private javax.swing.JTextField productNameField;
    private javax.swing.JTextField profitRateField;
    private javax.swing.JTextArea specificationsTextArea;
    private javax.swing.JTextField stockQuantityField;
    private javax.swing.JTextField warrantyField;
    // End of variables declaration//GEN-END:variables
}
